CREATE TABLESPACE TALLER_HIBERNATE
    DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\taller_hibernate.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

CREATE USER TALLER_HIBERNATE IDENTIFIED BY TALLER_HIBERNATE 
    DEFAULT TABLESPACE TALLER_HIBERNATE;

GRANT CREATE SESSION, ALTER SESSION, CREATE SEQUENCE, CREATE TABLE, 
    CREATE TABLESPACE, UNLIMITED TABLESPACE TO TALLER_HIBERNATE;