DROP USER TALLER_HIBERNATE CASCADE;
DROP TABLESPACE TALLER_HIBERNATE INCLUDING CONTENTS AND DATAFILES;

DROP TABLE T_CONTRACT;
DROP TABLE T_CLIENT;
DROP SEQUENCE SEQ_T_CLIENT;
DROP SEQUENCE SEQ_T_CONTRACT;